algo_cls: 'deq'
inv_ptr: False
jac_reg: True
use_GRANOLA: False
use_expander: False
GRANOLA_NRNF: 128
jac_reg_tau: 0.0001
contrastive_reg: False
hint_mode: 'none'
supervise_hints: False
max_epochs: 100
weight_decay: 0.00000
learn_termination: False
termination_overshoot_factor: 1.5
global_pool: 'max'
# decay_hidden: 0.9
deq:
  solver: 'anderson'
  stochastic: False
  stochastic_alpha: 0.5
  deq_max_iter: 40
  eval_factor: 4
  f_tol: 0.1
  b_tol: 0.01
  stop_mode: 'rel'
  align: True
  align_sv_on_normal: False
  alignment_factor: 0.01
  monotonise: False
  monoto_factor: 0.010
